---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: What are file permissions?
    - name: module-02
      label: Interacting with a file from different user accounts
    - name: module-03
      label: The chmod Command
    - name: module-04
      label: Changing permissions (symbolic)
    - name: module-05
      label: Changing permissions (absolute)
    - name: module-06
      label: Changing file ownership
    - name: module-07
      label: Changing Group Ownership
    - name: module-08
      label: Auditing permissions
tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel
